---
- name: Install openldap packages if needed
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  with_items: "{{ openldap }}"
  when: opdk_version | version_compare('4.17.01', '<')

- block:
  - name: Downgrade openldap packages if needed
    become: yes
    yum:
      name: "{{ item }}"
      state: present
      allow_downgrade: yes
    with_items: "{{ openldap_2_4_40 }}"
#    shell: "yum downgrade -y {{ openldap_2_4_40 | join(' ') }}"

#  - name: Update LDAP dependent libraries
#    file:
#      force: yes
#      state: link
#      src: "{{ item.src }}"
#      path: "{{ item.path }}"
#    with_items: "{{ ldap_dependent_library_links }}"

  rescue:
    - name: Download openldap manually, may need to change the link
      become: yes
      yum:
        name: "{{ item }}"
        state: present
        allow_downgrade: yes
      with_items: "{{ openldap_manual_download }}"
#      shell: "yum downgrade -y {{ openldap_manual_download | join(' ') }}"

#        - name: Update LDAP dependent libraries
#          file:
#            force: yes
#            state: link
#            src: "{{ item.src }}"
#            path: "{{ item.path }}"
#          with_items: "{{ ldap_dependent_library_links }}"

  when: opdk_version | version_compare('4.17.01', '>=') and opdk_version | version_compare('4.17.05', '<=')
