---
- name: Install openldap packages if needed with proxy
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ openldap }}"
  when: opdk_version | version_compare('4.17.01', '<')
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- block:
  - name: Downgrade openldap packages if needed with proxy
    become: yes
    shell: "yum downgrade -y {{ openldap_2_4_40 | join(' ') }}"
    environment:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }}"

  rescue:
    - name: Install because downgrade failure means the openldap packages are needed with proxy
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ openldap_2_4_40 }}"
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        no_proxy: "{{ no_proxy }}"
  when: opdk_version | version_compare('4.17.01', '>=') and opdk_version | version_compare('4.17.05', '<=')
