---
- name: Install openldap packages if needed
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ openldap }}"
  when: opdk_version | version_compare('4.17.05', '>')

#- block:
#- name: Downgrade openldap packages if needed
#  become: yes
#  yum:
#    name: "{{ item }}"
#    state: present
#    allow_downgrade: yes
#  with_items: "{{ openldap_2_4_40 }}"
#  when: opdk_version | version_compare('4.17.01', '>=') and opdk_version | version_compare('4.17.05', '<=')

- block:
  - name: Remove existing openldap packages
    yum:
      name: "{{ item }}"
      state: absent
    with_items: "{{ opendldap }}"

  - name: Clean yum cache
    shell: "yum clean all"

#  - name: Download openldap manually
#    shell: "rpm -Uvh --oldpackage {{ openldap_manual_download[0] }}"
#    args:
#      creates: /usr/lib64/liblber-2.4.so.2.10.3

#  - name: Remove prior openldap servers and clients
#    yum:
#      name: "{{ item  }}"
#      state: absent
#    with_items:
#    - "{{ openldap[1] }}"
#    - "{{ openldap[2] }}"

  - name: Download openldap manually, may need to change the link
    yum:
      name: "{{ item  }}"
      state: present
      allow_downgrade: yes
    with_items: "{{ openldap_manual_download }}"

  become: yes
  when: opdk_version | version_compare('4.17.05', '<=')

#  - name: Downgrade openldap packages if needed
#    become: yes
#    shell: "yum install -y {{ openldap_2_4_40 | join(' ') }}"

#  - name: Update LDAP dependent libraries
#    file:
#      force: yes
#      state: link
#      src: "{{ item.src }}"
#      path: "{{ item.path }}"
#    with_items: "{{ ldap_dependent_library_links }}"

#  rescue:
#    - name: Download openldap manually, may need to change the link
#      become: yes
#      yum:
#        name: "{{ item }}"
#        state: present
#        allow_downgrade: yes
#      with_items: "{{ openldap_manual_download }}"

#        - name: Update LDAP dependent libraries
#          file:
#            force: yes
#            state: link
#            src: "{{ item.src }}"
#            path: "{{ item.path }}"
#          with_items: "{{ ldap_dependent_library_links }}"

#  when: opdk_version | version_compare('4.17.01', '>=') and opdk_version | version_compare('4.17.05', '<=')
