---
- name: Install openldap packages if needed
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ openldap }}"
  when: opdk_version | version_compare('4.17.01', '<')

- block:
  - name: Downgrade openldap packages if needed
    become: yes
    shell: "yum downgrade -y {{ openldap_2_4_40 | join(' ') }}"

  rescue:
    - name: Install because downgrade failure means the openldap packages are needed
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ openldap_2_4_40 }}"
  when: opdk_version | version_compare('4.17.01', '>=') and opdk_version | version_compare('4.17.05', '<=')
